server:
  port: 14999

spring:
  application:
    name: oauth2-server
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.105:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.0.105:8848
        file-extension: yaml
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql//localhost:3306/oauth?characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: nacos
    password: nacos


