server:
  port: 14999

spring:
  application:
    name: oauth2-server
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.105:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.0.105:8848
        file-extension: yaml
        username: nacos
        password: nacos

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: oauth2-server-routes
          uri:
            lb://oauth2-server
          predicates:
            - Path=/**
          filters:
            - StripPrefix=1
